service: times-all-bot
frameworkVersion: '3'
provider:
  name: aws
  runtime: nodejs20.x
  region: ap-northeast-1
functions:
  slack:
    handler: index.handler
    events:
      - http:
          path: slack/events
          method: post
plugins:
  - serverless-offline
  - serverless-dotenv-plugin